In [31]:
import pandas as pd
import numpy as np


In [32]:
pip install xgboost

Note: you may need to restart the kernel to use updated packages.


In [33]:
dataset=pd.read_csv("Insurance.csv")

In [34]:
dataset

age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [35]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [36]:
dataset

age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [37]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [38]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dependent=dataset[['charges']]

In [39]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)


In [40]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [41]:
scy=StandardScaler()
y_train=scy.fit_transform(y_train)
y_test=scy.transform(y_test)

In [46]:
from sklearn.model_selection import GridSearchCV
from xgboost import XGBRegressor


param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [3, 5],
    'learning_rate': [0.01, 0.05],
    'subsample': [0.8, 1],
    'colsample_bytree': [0.8, 1]
}


regressor = XGBRegressor(eval_metric='rmse', n_jobs=-1, use_label_encoder=False)

grid = GridSearchCV(estimator=regressor,
                    param_grid=param_grid,
                    cv=3,
                    verbose=3,
                    n_jobs=-1)


grid.fit(x_train, y_train)


Fitting 3 folds for each of 32 candidates, totalling 96 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 12 concurrent workers.
[Parallel(n_jobs=-1)]: Done   8 tasks      | elapsed:    3.1s
[Parallel(n_jobs=-1)]: Done  96 out of  96 | elapsed:    6.0s finished


GridSearchCV(cv=3, error_score='raise-deprecating',
             estimator=XGBRegressor(base_score=None, booster=None,
                                    callbacks=None, colsample_bylevel=None,
                                    colsample_bynode=None,
                                    colsample_bytree=None,
                                    early_stopping_rounds=None,
                                    enable_categorical=False,
                                    eval_metric='rmse', gamma=None, gpu_id=None,
                                    grow_policy=None, importance_type=None,
                                    interaction_constraints=None,
                                    learn...
                                    n_jobs=-1, num_parallel_tree=None,
                                    objective='reg:squarederror',
                                    predictor=None, random_state=None,
                                    reg_alpha=None, ...),
             iid='warn', n_

In [47]:
re=grid.cv_results_
grid_predictions=grid.predict(x_test)
print("The R_score value for best parameter{}: ".format(grid.best_params_))

The R_score value for best parameter{'colsample_bytree': 1, 'learning_rate': 0.05, 'max_depth': 3, 'n_estimators': 100, 'subsample': 1}: 


In [48]:
table=pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.089250      0.007408         0.009453        0.006788   
1        0.110964      0.021432         0.000000        0.000000   
2        0.385613      0.113859         0.006055        0.006980   
3        0.578729      0.002311         0.007444        0.007945   
4        0.252824      0.080343         0.010436        0.007380   
5        0.345433      0.024229         0.006877        0.006514   
6        0.705052      0.001925         0.003723        0.005265   
7        0.672645      0.010926         0.010183        0.009531   
8        0.341569      0.020637         0.009883        0.007020   
9        0.338904      0.004995         0.009349        0.004939   
10       0.548949      0.006640         0.006865        0.006589   
11       0.566331      0.006718         0.010467        0.007510   
12       0.245895      0.006687         0.011854        0.003829   
13       0.260924      0.017996         0.007466        0.006541   
14       0.600502      0.009169         0.010414        0.007364   
15       0.560921      0.007375         0.015628        0.000000   
16       0.259417      0.009364         0.000000        0.000000   
17       0.218936      0.000670         0.005207        0.007364   
18       0.502700      0.013100         0.000000        0.000000   
19       0.471528      0.033346         0.010979        0.006882   
20       0.246388      0.045236         0.000000        0.000000   
21       0.247443      0.025013         0.005346        0.004118   
22       0.321684      0.129974         0.000000        0.000000   
23       0.258557      0.130773         0.000000        0.000000   
24       0.226751      0.014905         0.005208        0.007366   
25       0.195409      0.007505         0.005215        0.007375   
26       0.163028      0.007862         0.005216        0.007377   
27       0.407723      0.039437         0.002062        0.002916   
28       0.256314      0.015047         0.000000        0.000000   
29       0.215122      0.025846         0.000000        0.000000   
30       0.353143      0.063247         0.000000        0.000000   
31       0.339430      0.018514         0.006400        0.006686   

   param_colsample_bytree param_learning_rate param_max_depth  \
0                     0.8                0.01               3   
1                     0.8                0.01               3   
2                     0.8                0.01               3   
3                     0.8                0.01               3   
4                     0.8                0.01               5   
5                     0.8                0.01               5   
6                     0.8                0.01               5   
7                     0.8                0.01               5   
8                     0.8                0.05               3   
9                     0.8                0.05               3   
10                    0.8                0.05               3   
11                    0.8                0.05               3   
12                    0.8                0.05               5   
13                    0.8                0.05               5   
14                    0.8                0.05               5   
15                    0.8                0.05               5   
16                      1                0.01               3   
17                      1                0.01               3   
18                      1                0.01               3   
19                      1                0.01               3   
20                      1                0.01               5   
21                      1                0.01               5   
22                      1                0.01               5   
23                      1                0.01               5   
24                      1                0.05               3   
25                      1                0.05               3   
26  

In [49]:
print("✅ Best Score (CV):", grid.best_score_)


✅ Best Score (CV): 0.8346091285847963


In [50]:
y_pred = grid.predict(x_test)
from sklearn.metrics import r2_score
r_score = r2_score(y_test, y_pred)
print("r² Score:", r_score)

r² Score: 0.8939704010409936


In [51]:
import pickle
filename="finalized_model_xgboostingRegression.sav"

In [52]:
pickle.dump(grid.best_estimator_, open(filename, 'wb'))

In [53]:
preinput=sc.transform([[25,20,2,1,1]])

In [54]:
preinput

array([[-1.03919296, -1.72664148,  0.75672907,  1.01127431,  2.00280702]])

In [55]:
loaded_model=pickle.load(open("finalized_model_xgboostingRegression.sav",'rb'))
result=loaded_model.predict(preinput)
result

array([0.308738], dtype=float32)

In [56]:
preoutput=scy.inverse_transform([result])

In [57]:
preoutput

array([[16786.062]], dtype=float32)